apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}-pod
  labels:
    app: {{.Name}}
spec:
  volumes:
  - name: shared-data
    hostPath:
      path: /Users/espenak/code/kubewrr/shared_data
  terminationGracePeriodSeconds: 4
  containers:
  - name: {{.Name}}-miniserver
    image: {{.Name}}-miniserver
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-data
      mountPath: /hostdata
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}--miniserver-service
  labels:
    app: {{.Name}}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{.Name}}-miniserver
  type: LoadBalancer
