apiVersion: v1
kind: Pod
metadata:
  name: {{.FullName}}-pod
  labels:
    app: {{.FullName}}
spec:
  volumes:
  - name: shared-data
    hostPath:
      path: {{.Path "shared_files"}}
  terminationGracePeriodSeconds: 4
  containers:
  - name: {{.FullName}}-miniserver
    image: {{.FullName}}-miniserver
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-data
      mountPath: /hostdata
---
apiVersion: v1
kind: Service
metadata:
  name: {{.FullName}}--miniserver-service
  labels:
    app: {{.FullName}}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{.FullName}}-miniserver
  type: LoadBalancer
